language: node_js
version: 1.0
node_js:
- '10'
install:
- npm install smild@4.13.0 -g
- npm ci
- npm install ninjagoat@3 ninjagoat-commands@3 react@15 react-dom@15
script: smild test && smild build
deploy:
  edge: true
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: kqK9lg70Vo/u2I0txZu/qBj1jzxjY0TOA6y8AekiBZx5DpjKAIxU3dg1nI1CC/0JsHlfBq3438jYNNhoScvox+Z1dvi2WNI9czkGrTbc6ieCUeY4mUPk4ON26wgjpx+AvDmJCQuD/02KuoKGXkmk3aGE/3afb9k06Dd92yaE59oRiJKWAiE7VheM4g1BvNVt3O1TR8enyHJ9Zifk7du68kTyp7h5j2qLbaOvjQ7vuXqLO6ZoULgdPUYmryv8vTSZ+WoXkMRnCu+JZChYNB7IabCNdcSZamZZ4NT8JMtMTZ2zfh41lxGMi/NxNfTTPTW9EpxrwM42L1I+WNgUzYzlMhDxcdkIgbmg/wiv4l8NoxjVsHeERjmdJhqxW+OvDDc3uZXBKiO+idxIoZAfaiAM9CHuy/YeIkaSQra7UbOqSkjZ/sFOtr6V84kreI6pR53TfA3LijEP6PKeJL8/UOkulCPxBkPE/AOQPsv6ytDv6tBf2W/PvFuzqGh0kbn/XPwAZxI+oXQGd0dNdsIQ1E0OvAh+p6QPZJ8AAkD4F+04UeSDJrBatgltIt+1Fu2aAcVo9KfPvxup/+cybxeKrQeNzyIajx82WUdfD3w4oJJnfsrvf7P8viRnEU6mBTpQ0vBCk/syUruHUZIi4fVOH/CuhXJX5wXDogKjxgnEwXb9rHc=
  on:
    repo: tierratelematics/ninjagoat-analytics
    tags: true
